export const CHANCE_CARDS = [
  { id:'c1',  text:'Перейдите на СТАРТ. Получите 200₽',                   action:{type:'goto',   pos:0,  collect:200} },
  { id:'c2',  text:'Идите в тюрьму. Не проходите Старт.',                 action:{type:'jail'} },
  { id:'c3',  text:'Получите дивиденды — 50₽',                            action:{type:'collect',amount:50} },
  { id:'c4',  text:'Ремонт дорог: 25₽ за дом, 100₽ за отель',            action:{type:'repairs', house:25,hotel:100} },
  { id:'c5',  text:'Штраф за превышение скорости — 15₽',                  action:{type:'pay',    amount:15} },
  { id:'c6',  text:'Ваши акции выросли! +150₽',                           action:{type:'collect',amount:150} },
  { id:'c7',  text:'Перейдите на Казанский вокзал (поз. 5)',               action:{type:'goto',   pos:5} },
  { id:'c8',  text:'Вы вышли из тюрьмы бесплатно! (карточка)',            action:{type:'jailFree'} },
  { id:'c9',  text:'Отступите на 3 клетки назад',                         action:{type:'back',   amount:3} },
  { id:'c10', text:'Налог на ремонт дорог — 100₽',                        action:{type:'pay',    amount:100} },
  { id:'c11', text:'Перейдите на Новый Арбат (поз. 24)',                   action:{type:'goto',   pos:24} },
  { id:'c12', text:'Перейдите на Рублёвский дворец (поз. 39)',             action:{type:'goto',   pos:39} },
  { id:'c13', text:'Банк платит вам 50₽',                                  action:{type:'collect',amount:50} },
  { id:'c14', text:'Первое место на конкурсе красоты — +10₽',             action:{type:'collect',amount:10} },
  { id:'c15', text:'Перейдите на Белорусский вокзал (поз. 25)',            action:{type:'goto',   pos:25} },
  { id:'c16', text:'Займ в банке — +200₽ (потом с процентами...)',         action:{type:'collect',amount:200} },
];

export const COMMUNITY_CARDS = [
  { id:'cc1',  text:'Перейдите на СТАРТ. Получите 200₽',                  action:{type:'goto',   pos:0,  collect:200} },
  { id:'cc2',  text:'Налог на наследство — 100₽',                         action:{type:'pay',    amount:100} },
  { id:'cc3',  text:'Страховые выплаты! +100₽',                           action:{type:'collect',amount:100} },
  { id:'cc4',  text:'Возврат налогов — +20₽',                             action:{type:'collect',amount:20} },
  { id:'cc5',  text:'День рождения! Каждый игрок платит вам 10₽',         action:{type:'birthday',amount:10} },
  { id:'cc6',  text:'Вышли из тюрьмы бесплатно! (карточка)',              action:{type:'jailFree'} },
  { id:'cc7',  text:'Выиграли в лотерею — +200₽!',                        action:{type:'collect',amount:200} },
  { id:'cc8',  text:'Расходы на больницу — 50₽',                          action:{type:'pay',    amount:50} },
  { id:'cc9',  text:'Идите в тюрьму. Не проходите Старт.',                action:{type:'jail'} },
  { id:'cc10', text:'Ремонт домов: 40₽/дом, 115₽/отель',                  action:{type:'repairs', house:40,hotel:115} },
  { id:'cc11', text:'Продали акции — +50₽',                               action:{type:'collect',amount:50} },
  { id:'cc12', text:'Сбор в школьный фонд — 150₽',                        action:{type:'pay',    amount:150} },
  { id:'cc13', text:'Банковская ошибка в вашу пользу — +200₽!',           action:{type:'collect',amount:200} },
  { id:'cc14', text:'Штраф за нарушение ПДД — 15₽',                       action:{type:'pay',    amount:15} },
  { id:'cc15', text:'Консультационные услуги — +25₽',                     action:{type:'collect',amount:25} },
  { id:'cc16', text:'Наследство от дальнего родственника — +100₽',        action:{type:'collect',amount:100} },
];
